### ISSUE TITLE
bug / enchant item with book

### ISSUE THREAD

**Issue by IPECTER** [JEFF-Media-GbR/StackResize#4]
![image](https://github.com/mfnalex/StackResize/assets/80433772/33ab6c91-129a-430c-953f-c8a5b94a9cdc)
Enchanting is success.
But remained 3 enchant book is disappeared..!!

**Comment by mfnalex** [comment]
Thanks, will be fixed next week (i‘m moving into a new apartment this weekend)

**Comment by IPECTER** [comment]
thx!

**Comment by IPECTER** [comment]
@mfnalex any news?

**Comment by mfnalex** [comment]
Fixed in 1.6.2
